-- Bartender Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-setup', 'Bar Setup', 'Preparing the bar', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>A well-prepared bar is the foundation of great service. Set up your station with intention: glassware polished, garnishes prepped, ice stocked, tools within reach. A calm setup leads to a confident service.</p>"}}]}'::jsonb, 4, 1),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'glassware-standards', 'Glassware Standards', 'The right glass matters', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Every drink deserves the right glass. Know your glassware: wine glasses, cocktail coupes, tumblers, highballs. Check every glass for chips, marks, and watermarks before use. Presentation starts with the vessel.</p>"}}]}'::jsonb, 3, 2),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'garnish-preparation', 'Garnish Preparation', 'Fresh and ready', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Prepare garnishes fresh at the start of each service. Cut citrus cleanly, keep herbs fresh, prepare specialty garnishes in advance. A well-garnished drink elevates the entire experience.</p>"}}]}'::jsonb, 3, 3),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'fridge-organisation', 'Fridge Organisation', 'Keeping stock accessible', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Organise fridges logically: most-used items at eye level, backup stock behind current stock, labels facing forward. A well-organised fridge speeds up service and reduces waste. Rotate stock consistently.</p>"}}]}'::jsonb, 3, 4),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'ice-management', 'Ice Management', 'The foundation of good drinks', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Ice is not an afterthought. Keep ice wells full throughout service. Use the right ice for each drink: cubed for spirits, crushed for certain cocktails. Handle ice hygienically, always using a scoop, never your hands.</p>"}}]}'::jsonb, 3, 5),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'wine-knowledge', 'Wine Knowledge', 'Understanding our wine list', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know the wines on our list: their region, grape variety, flavour profile, and ideal food pairings. Taste when you can, study what you cannot. Confidence with wine comes from genuine knowledge, not memorised scripts.</p>"}}]}'::jsonb, 5, 6),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'cocktail-knowledge', 'Cocktail Knowledge', 'Our cocktail offerings', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Master our cocktail menu. Know the ingredients, method, and story behind each drink. Practice your technique: shaking, stirring, muddling. Consistency in every pour builds trust and delivers excellence.</p>"}}]}'::jsonb, 5, 7),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'mocktail-knowledge', 'Mocktail Knowledge', 'Non-alcoholic excellence', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Non-alcoholic options deserve the same care and creativity as cocktails. Know our mocktail menu. Present them with the same pride and attention. Every guest deserves a beautiful drink, regardless of their preference.</p>"}}]}'::jsonb, 4, 8),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'spirits-knowledge', 'Spirits Knowledge', 'Understanding our spirits', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know the spirits behind the bar: their origin, character, and best use. Understand the difference between a house pour and a premium selection. Be ready to recommend with confidence when a guest asks.</p>"}}]}'::jsonb, 4, 9),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'beer-knowledge', 'Beer Knowledge', 'Our beer selection', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know our beer selection: styles, breweries, and serving temperatures. Understand the difference between lagers, ales, IPAs, and stouts. Pour with care and serve at the correct temperature.</p>"}}]}'::jsonb, 3, 10),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'taking-drink-orders', 'Taking Drink Orders', 'Engaging with guests', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Approach drink orders with warmth and knowledge. Ask open questions to understand preferences. Suggest options that match what they enjoy. Taking a drink order is the beginning of a conversation, not a transaction.</p>"}}]}'::jsonb, 3, 11),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'responsible-service', 'Responsible Service of Alcohol', 'Legal and ethical responsibility', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Responsible service of alcohol is a legal and ethical obligation. Know the signs of intoxication. Refuse service when necessary, with dignity and respect. Follow all RSA guidelines. The safety of our guests is always the priority.</p>"}}]}'::jsonb, 4, 12),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-guest-interaction', 'Guest Interaction', 'Connection at the bar', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The bar is a place of connection. Engage with guests naturally. Read the room: some guests want conversation, others want quiet. Be available without hovering. Make every guest feel welcome at our bar.</p>"}}]}'::jsonb, 3, 13),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-recommendations', 'Recommendations', 'Guiding choices', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>When recommending drinks, listen first. Understand what the guest enjoys, then suggest from genuine knowledge. Share your personal favourites. Authentic recommendations build trust and enhance the experience.</p>"}}]}'::jsonb, 3, 14),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-opening-ritual', 'Opening Ritual', 'Setting up for success', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Follow the bar opening checklist with care. Stock the bar, prepare garnishes, check equipment, polish glassware. A thorough opening sets the tone for a smooth and confident service.</p>"}}]}'::jsonb, 4, 15),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-closing-ritual', 'Closing Ritual', 'End of night procedures', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Close the bar with the same care you opened it. Clean all surfaces, wash and polish glassware, restock for tomorrow. Complete the closing checklist fully. A well-closed bar is ready for a fresh start.</p>"}}]}'::jsonb, 4, 16),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'bar-cleaning-standards', 'Cleaning Standards', 'Maintaining hygiene', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clean as you go throughout service. Wipe surfaces regularly, keep drains clear, and maintain hygiene at all times. A clean bar is a safe bar. Standards must be consistent, not just at close, but throughout the night.</p>"}}]}'::jsonb, 3, 17),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'stock-management', 'Stock Management', 'Tracking and ordering', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Monitor stock levels throughout service. Flag low items early. Understand par levels and ordering procedures. Good stock management prevents mid-service shortages and ensures consistency for every guest.</p>"}}]}'::jsonb, 3, 18),
('6eddec72-3a9d-40ad-8e5c-3f5fe59e12a7', 'end-of-night-procedures', 'End of Night Procedures', 'Final checks', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Complete all end-of-night procedures: cash up if required, secure stock, check that all equipment is off and clean. Report any issues or breakages. Leave the bar in a state you would be proud to walk into tomorrow.</p>"}}]}'::jsonb, 3, 19)
ON CONFLICT (path_id, slug) DO NOTHING;

-- General Kitchen Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'professional-standards', 'Professional Standards', 'Kitchen professionalism', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>A professional kitchen runs on respect, discipline, and pride. Arrive on time, in clean uniform, ready to work. Communicate clearly. Support your team. Take ownership of your station and your work.</p>"}}]}'::jsonb, 3, 1),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'kitchen-communication', 'Communication', 'Clear kitchen communication', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Communication in the kitchen must be clear, concise, and timely. Call out when you are behind, when you need support, and when orders are ready. Use standard kitchen language. Good communication prevents mistakes and keeps service flowing.</p>"}}]}'::jsonb, 3, 2),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'teamwork', 'Teamwork', 'Working together', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The kitchen is a team. No single person can deliver a great service alone. Support each other during rushes, share knowledge, and lift each other up. When the team works well together, everything flows.</p>"}}]}'::jsonb, 3, 3),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'food-handling', 'Food Handling', 'Safe food practices', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Handle all food with clean hands and appropriate tools. Use gloves when required. Store food correctly: raw below cooked, labelled and dated. Follow FIFO principles. Safe food handling protects our guests and our reputation.</p>"}}]}'::jsonb, 4, 4),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'temperature-control', 'Temperature Control', 'Keeping food safe', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Monitor temperatures diligently. Hot food must stay hot, cold food must stay cold. Record fridge and freezer temperatures daily. Understand the danger zone and why it matters. Temperature control is non-negotiable.</p>"}}]}'::jsonb, 4, 5),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'cross-contamination', 'Cross Contamination', 'Preventing contamination', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Prevent cross contamination at every step. Use separate cutting boards for raw and cooked. Wash hands between tasks. Store allergens separately. Understanding contamination risks keeps our guests safe.</p>"}}]}'::jsonb, 4, 6),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'hygiene-standards', 'Hygiene Standards', 'Personal and kitchen hygiene', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Maintain the highest personal hygiene standards. Wash hands frequently, keep nails short and clean, tie back hair. Clean your station continuously. Hygiene is the foundation of a trustworthy kitchen.</p>"}}]}'::jsonb, 3, 7),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'docket-flow', 'Docket Flow', 'Managing orders', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Understand how dockets flow through the kitchen. Read dockets carefully, noting modifications and allergies. Communicate timing with your section. Docket management is the heartbeat of a smooth service.</p>"}}]}'::jsonb, 4, 8),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'service-communication', 'Service Communication', 'Talking during service', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>During service, communication must be direct and efficient. Call out clearly when dishes are ready. Respond when called. Keep the chef informed of any delays or issues. Silence in a kitchen creates confusion.</p>"}}]}'::jsonb, 3, 9),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'working-with-foh', 'Working With Front Of House', 'Kitchen-floor partnership', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The kitchen and front of house are partners, not separate teams. Respect the floor team. Communicate dish timing, flag delays, and work together to deliver a seamless guest experience. When kitchen and floor align, the guest feels it.</p>"}}]}'::jsonb, 3, 10),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'prep-standards', 'Prep Standards', 'Consistent preparation', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Prep is the foundation of every great dish. Follow recipes precisely. Cut consistently, measure accurately, and label everything. Good prep means smooth service and consistent quality for every guest.</p>"}}]}'::jsonb, 4, 11),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'portion-control', 'Portion Control', 'Consistency in every serve', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Every dish must be portioned consistently. Use scales, measures, and portion guides. Consistency means every guest receives the same quality, regardless of who is cooking or when they are dining.</p>"}}]}'::jsonb, 3, 12),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'recipe-consistency', 'Recipe Consistency', 'Following the standard', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Recipes are our standard. Follow them precisely, every time. If something needs adjustment, discuss it with the head chef. Consistency builds trust with our guests. They should experience the same quality on every visit.</p>"}}]}'::jsonb, 3, 13),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'plating-standards', 'Plating Standards', 'Visual presentation', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Plating is the final step before a dish reaches the guest. Follow the plating guide for each dish. Wipe plate rims clean. Arrange garnishes with intention. A beautifully plated dish honours the effort behind it.</p>"}}]}'::jsonb, 3, 14),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'kitchen-cleaning-standards', 'Cleaning Standards', 'A clean kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clean as you go is not optional. Wipe surfaces between tasks. Sweep floors regularly. Deep clean at the end of every shift. A clean kitchen is a safe kitchen, and a safe kitchen produces great food.</p>"}}]}'::jsonb, 3, 15),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'kitchen-opening-ritual', 'Kitchen Opening Ritual', 'Starting service right', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Follow the kitchen opening checklist. Check deliveries, set up stations, prepare mise en place. Test equipment. Brief the team on the menu and any specials. A calm, thorough opening leads to a confident service.</p>"}}]}'::jsonb, 4, 16),
('ed1a7e46-afc4-4eba-856b-646c75c1be4c', 'kitchen-closing-ritual', 'Kitchen Closing Ritual', 'Ending the night well', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Close the kitchen with care and thoroughness. Clean all stations, put away stock, label and date prep items. Complete the closing checklist. Leave the kitchen in a state that makes tomorrow easier.</p>"}}]}'::jsonb, 4, 17)
ON CONFLICT (path_id, slug) DO NOTHING;
