-- Seed employment document templates for the Academy documents system
INSERT INTO academy_document_templates (slug, title, description, category, requires_signature, sort_order, template_content) VALUES
('personal-details', 'Personal Details', 'Collect personal information, address, and contact details', 'personal_info', false, 1, '{"fields":["first_name","last_name","date_of_birth","address_line_1","address_line_2","suburb","state","postcode","phone"]}'::jsonb),
('emergency-contact', 'Emergency Contact', 'Emergency contact person and relationship', 'personal_info', false, 2, '{"fields":["emergency_contact_name","emergency_contact_phone","emergency_contact_relationship"]}'::jsonb),
('bank-details', 'Bank Details', 'Bank account information for payroll', 'personal_info', false, 3, '{"fields":["bank_bsb","bank_account_number","bank_account_name"]}'::jsonb),
('super-details', 'Superannuation Details', 'Super fund information', 'personal_info', false, 4, '{"fields":["super_fund_name","super_member_number","super_usi"]}'::jsonb),
('employment-offer', 'Employment Offer Letter', 'Formal offer of employment at Still and Social', 'employment', true, 5, '{"body":"This letter confirms our offer of employment at Still and Social. The details of your role, hours, and remuneration are outlined below. Please review carefully and sign to accept."}'::jsonb),
('employment-contract', 'Employment Contract', 'Full employment contract with terms and conditions', 'employment', true, 6, '{"body":"This Employment Contract outlines the terms and conditions of your employment with Still and Social. By signing, you confirm your acceptance of the role, responsibilities, and conditions described within."}'::jsonb),
('staff-handbook', 'Staff Handbook Acknowledgement', 'Confirm receipt and understanding of the staff handbook', 'policy', true, 7, '{"body":"By signing this document, you confirm that you have received, read, and understood the Still and Social Staff Handbook. You agree to abide by the policies, procedures, and standards outlined within."}'::jsonb),
('workplace-policies', 'Workplace Policies', 'Acknowledgement of workplace policies including WHS, RSA, and privacy', 'policy', true, 8, '{"body":"By signing this document, you acknowledge that you have been provided with and understand the Still and Social workplace policies, including workplace health and safety, anti-discrimination, responsible service of alcohol, social media, and privacy policies."}'::jsonb),
('position-description', 'Position Description', 'Acknowledgement of role responsibilities and expectations', 'employment', true, 9, '{"body":"This document outlines the key responsibilities, duties, and expectations of your position at Still and Social. By signing, you confirm that you understand your role and agree to perform your duties to the standards described."}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
