-- Kitchen Hand Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('24990561-b9db-43ff-b94e-1436dec94fa7', 'dishwashing-standards', 'Dishwashing Standards', 'Clean and efficient', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Dishwashing is essential to service. Scrape, rinse, wash, sanitise, and dry with care. Keep the dish pit organised and flowing. Prioritise items the kitchen needs most. Speed and cleanliness go hand in hand.</p>"}}]}'::jsonb, 3, 1),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'kh-cleaning-standards', 'Cleaning Standards', 'Maintaining the kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Keep all kitchen surfaces, floors, and equipment clean throughout service. Follow the cleaning schedule. Use the correct chemicals for each task. A clean kitchen supports safe, high-quality food production.</p>"}}]}'::jsonb, 3, 2),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'bin-management', 'Bin Management', 'Waste handling', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Empty bins before they overflow. Separate waste correctly: general, recycling, and organic. Replace bin liners immediately. Keep the bin area clean and tidy at all times.</p>"}}]}'::jsonb, 3, 3),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'basic-food-prep', 'Basic Food Prep', 'Supporting the chefs', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Learn basic prep tasks: washing vegetables, peeling, portioning ingredients. Follow instructions precisely. Ask questions when unsure. Good prep skills are the first step to growing in the kitchen.</p>"}}]}'::jsonb, 4, 4),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'stock-organisation', 'Stock Organisation', 'Keeping stock in order', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Organise stock logically: labels forward, oldest at front. Unpack deliveries promptly and store correctly. Report damaged or expired items immediately. Good stock management reduces waste and supports the kitchen.</p>"}}]}'::jsonb, 3, 5),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'supporting-chefs', 'Supporting Chefs', 'Being a reliable team member', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Listen to the chefs and respond quickly. Anticipate what they need: clean pans, prepped ingredients, clear bench space. Being a great kitchen hand means making the chefs job easier so they can focus on the food.</p>"}}]}'::jsonb, 3, 6),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'kh-safety-procedures', 'Safety Procedures', 'Staying safe in the kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know the safety procedures: where the fire extinguisher is, how to handle burns, what to do in an emergency. Wear appropriate footwear. Report hazards immediately. Safety is everyones responsibility.</p>"}}]}'::jsonb, 3, 7),
('24990561-b9db-43ff-b94e-1436dec94fa7', 'end-of-night-cleaning', 'End of Night Cleaning', 'Closing the kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Complete all end-of-night cleaning tasks: deep clean the dish pit, mop floors, empty all bins, wipe down all surfaces. Follow the closing checklist. Leave everything ready for a fresh start tomorrow.</p>"}}]}'::jsonb, 4, 8)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Entree Chef Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'entree-prep', 'Entree Prep', 'Preparing entree items', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Prepare all entree components with precision. Follow recipes exactly, portion consistently, and have everything ready before service begins. Thorough prep is the foundation of a confident entree service.</p>"}}]}'::jsonb, 4, 1),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'fryer-safety', 'Fryer Safety', 'Safe fryer operation', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The fryer demands respect. Check oil levels and temperature before use. Lower food gently to prevent splashing. Never leave the fryer unattended. Know the emergency procedures for oil fires. Safety comes first, always.</p>"}}]}'::jsonb, 4, 2),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'ec-plating-standards', 'Plating Standards', 'Beautiful presentation', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Plate each entree according to the plating guide. Clean plate rims before service. Arrange garnishes with care. Consistency in plating means every guest receives the same beautiful dish.</p>"}}]}'::jsonb, 3, 3),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'ec-portion-control', 'Portion Control', 'Consistent portions', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Use scales and measures for every component. Consistent portions ensure quality, control costs, and build guest trust. If it looks different from the standard, adjust before it leaves the pass.</p>"}}]}'::jsonb, 3, 4),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'ec-sauce-standards', 'Sauce Standards', 'Perfect sauces every time', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Sauces must be consistent in flavour, texture, and temperature. Taste before serving. Adjust seasoning when needed. Apply sauces to plates cleanly and with intention. A great sauce elevates the entire dish.</p>"}}]}'::jsonb, 3, 5),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'ec-garnish-standards', 'Garnish Standards', 'Finishing touches', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Garnishes are not decoration. They are part of the dish. Use fresh, quality garnishes. Place them with intention according to the plating guide. A well-garnished dish shows attention to every detail.</p>"}}]}'::jsonb, 3, 6),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'docket-timing', 'Docket Timing', 'Managing your timing', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Read dockets as soon as they arrive. Plan your timing to coordinate with other stations. Communicate with the expo when you are ready or if you need more time. Good timing keeps the entire service flowing smoothly.</p>"}}]}'::jsonb, 4, 7),
('addfcc87-e079-43e7-8da3-70aa50aded0e', 'communication-with-expo', 'Communication With Expo', 'Working with the pass', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Keep the expo chef informed at all times. Call out when dishes are ready. Flag any delays immediately. Listen for calls and respond clearly. Strong communication between entree and expo ensures a seamless flow.</p>"}}]}'::jsonb, 3, 8)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Wok Chef Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wok-station-setup', 'Wok Station Setup', 'Preparing your station', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Set up your wok station with everything within reach: sauces, proteins, vegetables, utensils, and garnishes. A well-organised station allows you to move quickly and confidently during service.</p>"}}]}'::jsonb, 4, 1),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wok-safety', 'Wok Safety', 'Safe wok practices', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The wok station runs at extreme heat. Handle woks with dry cloths, never wet. Be aware of flames and oil splatter. Keep your station clean and clear of hazards. Respect the heat and it will serve you well.</p>"}}]}'::jsonb, 4, 2),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'heat-management', 'Heat Management', 'Controlling the wok', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Understanding heat is the core skill of wok cooking. Know when to use high heat for searing and when to reduce for sauces. Control the flame, control the timing, control the dish. Mastery comes with practice and attention.</p>"}}]}'::jsonb, 4, 3),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wk-sauce-standards', 'Sauce Standards', 'Consistent wok sauces', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Wok sauces must coat evenly and taste consistent every time. Measure accurately, add at the right moment, and toss thoroughly. The sauce should enhance, not overpower. Taste and adjust before plating.</p>"}}]}'::jsonb, 3, 4),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wk-portion-control', 'Portion Control', 'Consistent servings', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Portion proteins and vegetables accurately before cooking. Use scales and measures. Consistent portions mean consistent dishes and consistent costs. Every serve should look and taste the same.</p>"}}]}'::jsonb, 3, 5),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'timing-and-speed', 'Timing and Speed', 'Moving with purpose', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Wok cooking demands speed and precision. Prepare ingredients in advance so you can focus on the cook. Move with purpose but not panic. Good timing means dishes arrive at the pass hot and fresh.</p>"}}]}'::jsonb, 3, 6),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wk-plating-standards', 'Plating Standards', 'Presentation from the wok', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Transfer wok dishes to plates with care. Follow the plating guide for arrangement and garnish. Wipe plate rims clean. Even in a fast-paced station, presentation must not be compromised.</p>"}}]}'::jsonb, 3, 7),
('0c4257ec-a61b-4deb-9e1e-b3b5057ac439', 'wk-station-cleaning', 'Station Cleaning', 'Clean as you go', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clean your wok and station between dishes when possible. Wipe down surfaces, clear scraps, and maintain order. A clean station during service means faster, safer, and more consistent cooking.</p>"}}]}'::jsonb, 3, 8)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Curries Chef Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('a6edca0f-d955-498a-918a-4178c991ab57', 'curry-station-setup', 'Curry Station Setup', 'Preparing your station', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Set up your curry station with all bases, proteins, garnishes, and accompaniments ready. Check temperatures of holding items. Ensure rice is prepared and portioned. Organisation is the key to a smooth curry service.</p>"}}]}'::jsonb, 4, 1),
('a6edca0f-d955-498a-918a-4178c991ab57', 'curry-base-knowledge', 'Curry Base Knowledge', 'Understanding our curries', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know each curry base intimately: its spice profile, heat level, and key ingredients. Understand how to adjust consistency and seasoning. Every curry should taste as it was designed, every single time.</p>"}}]}'::jsonb, 4, 2),
('a6edca0f-d955-498a-918a-4178c991ab57', 'rice-standards', 'Rice Standards', 'Perfect rice every time', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Rice must be cooked to the correct texture and temperature. Portion consistently using the standard measure. Keep rice fresh and hot throughout service. Great rice is the foundation of a great curry dish.</p>"}}]}'::jsonb, 3, 3),
('a6edca0f-d955-498a-918a-4178c991ab57', 'cc-sauce-consistency', 'Sauce Consistency', 'Perfect sauce every time', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Curry sauces must be consistent in thickness, colour, and flavour. Stir regularly, adjust heat to prevent burning, and taste frequently. If a sauce is too thick or thin, correct it before plating.</p>"}}]}'::jsonb, 3, 4),
('a6edca0f-d955-498a-918a-4178c991ab57', 'cc-portion-control', 'Portion Control', 'Consistent servings', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Portion curry, rice, and accompaniments using the standard measures. Every dish should look the same and satisfy the same way. Consistency is what brings guests back.</p>"}}]}'::jsonb, 3, 5),
('a6edca0f-d955-498a-918a-4178c991ab57', 'cc-garnish-standards', 'Garnish Standards', 'Finishing the dish', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Garnish each curry dish according to the plating guide. Fresh herbs, appropriate accompaniments, and clean presentation. Garnishes complete the dish both visually and in flavour.</p>"}}]}'::jsonb, 3, 6),
('a6edca0f-d955-498a-918a-4178c991ab57', 'cc-plating-standards', 'Plating Standards', 'Beautiful curry presentation', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Plate curries with care. Place rice neatly, pour sauce with control, and arrange garnishes with intention. Clean plate rims. A well-plated curry elevates the entire dining experience.</p>"}}]}'::jsonb, 3, 7),
('a6edca0f-d955-498a-918a-4178c991ab57', 'cc-service-timing', 'Service Timing', 'Coordinating with the kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Coordinate your timing with other stations and the expo. Curry dishes should arrive at the pass hot and fresh. Communicate with the team about timing. Plan ahead so nothing sits waiting.</p>"}}]}'::jsonb, 3, 8)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Expo Chef Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'reading-dockets', 'Reading Dockets', 'Understanding every order', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Read every docket carefully as it arrives. Note table numbers, modifications, allergies, and special requests. A misread docket leads to mistakes that affect the guest. Accuracy starts at the pass.</p>"}}]}'::jsonb, 4, 1),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'calling-dockets', 'Calling Dockets', 'Clear communication', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Call dockets clearly and with authority. Ensure every station hears and confirms. Repeat modifications and allergies. The expo sets the rhythm of service. Clear calling keeps everyone aligned.</p>"}}]}'::jsonb, 4, 2),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'managing-service-flow', 'Managing Service Flow', 'Orchestrating the kitchen', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The expo manages the flow of the entire kitchen. Balance multiple tables, coordinate timing between stations, and ensure dishes leave together. Think ahead. Anticipate bottlenecks before they happen.</p>"}}]}'::jsonb, 5, 3),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'quality-control', 'Quality Control', 'Every dish must be perfect', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Check every dish before it leaves the kitchen. Temperature, presentation, portion, garnish. If something is not right, send it back. The expo is the last line of quality control. Nothing substandard reaches the guest.</p>"}}]}'::jsonb, 4, 4),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'plating-checks', 'Plating Checks', 'Final visual inspection', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Inspect plating against the standard for every dish. Check garnish placement, sauce application, and plate cleanliness. Wipe rims. Adjust anything that does not meet the standard before calling the dish.</p>"}}]}'::jsonb, 3, 5),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'timing-management', 'Timing Management', 'Keeping service on track', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Monitor the timing of every table. Know when entrees should follow starters, when mains should fire. Communicate with stations early. A well-timed service means guests never wait too long or feel rushed.</p>"}}]}'::jsonb, 4, 6),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'expo-communication-with-foh', 'Communication With FOH', 'Bridging kitchen and floor', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The expo is the bridge between kitchen and floor. Communicate dish readiness clearly to runners. Flag timing issues that might affect the guest experience. Strong expo-FOH communication creates seamless service.</p>"}}]}'::jsonb, 3, 7),
('ab6f6c70-9b5d-4126-89b9-53807d1957d8', 'final-dish-approval', 'Final Dish Approval', 'The last check', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Before any dish leaves the pass, give it your final approval. Does it look right? Is it hot? Is it complete? The expo signature is your guarantee of quality. Own it with pride and accountability.</p>"}}]}'::jsonb, 3, 8)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Supervisor Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'leading-by-example', 'Leading By Example', 'Setting the standard', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The best leaders lead by doing, not just directing. Arrive early, work hard, maintain standards, and treat everyone with respect. Your team watches how you behave more than what you say. Be the standard you expect.</p>"}}]}'::jsonb, 4, 1),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'shift-leadership', 'Shift Leadership', 'Running a shift', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>As shift leader, you set the tone. Brief the team clearly, assign positions, and monitor the floor throughout service. Stay calm under pressure. Your composure creates confidence in the team.</p>"}}]}'::jsonb, 5, 2),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'sv-venue-standards', 'Venue Standards', 'Maintaining excellence', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Walk the venue with fresh eyes every shift. Check table settings, lighting, music, bathrooms, and cleanliness. Address issues immediately. The venue standard is your responsibility when you are on shift.</p>"}}]}'::jsonb, 4, 3),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'sv-team-communication', 'Team Communication', 'Keeping the team informed', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Communicate clearly with your team before, during, and after service. Share important information: bookings, VIPs, menu changes, and any issues. Good communication prevents problems and builds trust.</p>"}}]}'::jsonb, 4, 4),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'guest-recovery', 'Guest Recovery', 'Turning problems into opportunities', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>When something goes wrong, respond quickly and with empathy. Listen to the guest fully, apologise sincerely, and offer a genuine solution. A well-handled complaint can create a more loyal guest than a perfect visit.</p>"}}]}'::jsonb, 5, 5),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'handling-difficult-situations', 'Handling Difficult Situations', 'Staying calm under pressure', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Difficult situations will arise. Stay calm, listen first, and assess before responding. Never argue with a guest. De-escalate with empathy and professionalism. Seek support from management when needed.</p>"}}]}'::jsonb, 5, 6),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'supporting-new-team-members', 'Supporting New Team Members', 'Mentoring and guiding', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Welcome new team members warmly. Show them how things work, be patient with questions, and check in regularly. A supportive start builds confidence and loyalty. Remember what it felt like to be new.</p>"}}]}'::jsonb, 4, 7),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'managing-breaks', 'Managing Breaks', 'Fair and timely', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Schedule breaks fairly and ensure everyone gets their allocated time. Manage the floor so breaks do not affect service. Check in with the team about their energy levels. Looking after your team is part of leading well.</p>"}}]}'::jsonb, 3, 8),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'sv-end-of-night-checks', 'End of Night Checks', 'Closing with care', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Walk the entire venue at close. Check all areas: dining rooms, bathrooms, kitchen, bar, storage. Ensure everything is clean, secure, and ready for tomorrow. Sign off on the closing checklist.</p>"}}]}'::jsonb, 4, 9),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'sv-opening-procedures', 'Opening Procedures', 'Starting the day right', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Arrive before the team. Walk the venue, check the booking sheet, and prepare the briefing. Ensure everything is set up and ready before the team arrives. A prepared supervisor creates a calm opening.</p>"}}]}'::jsonb, 4, 10),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'sv-closing-procedures', 'Closing Procedures', 'Securing the venue', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Oversee the entire closing process. Ensure all checklists are completed, all staff have clocked out, all doors and windows are secure. Complete the supervisor closing report. You are the last to leave.</p>"}}]}'::jsonb, 4, 11),
('7af19cb2-1309-4be8-b475-f7ab6ffa66d2', 'daily-briefings', 'Daily Briefings', 'Setting the team up', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Run a brief, focused team briefing before each service. Cover bookings, specials, VIPs, any issues from the previous shift, and the focus for tonight. Keep it positive and clear. A good briefing aligns the team.</p>"}}]}'::jsonb, 4, 12)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Management Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'recruitment', 'Recruitment', 'Finding the right people', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Recruit for values first, skills second. Look for warmth, reliability, and a genuine desire to care for others. Write clear job descriptions, use consistent criteria, and always represent the Still and Social brand in how you hire.</p>"}}]}'::jsonb, 5, 1),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'interview-process', 'Interview Process', 'Conducting interviews', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Interviews should be structured, fair, and welcoming. Ask consistent questions focused on values, experience, and scenarios. Give candidates a genuine sense of what it is like to work here. The interview is their first impression of us as a workplace.</p>"}}]}'::jsonb, 5, 2),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'trial-shift-process', 'Trial Shift Process', 'Evaluating in practice', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Trial shifts should be structured and supervised. Brief the candidate on what to expect. Assign a buddy. Observe how they interact with guests and the team. Provide feedback at the end, regardless of the outcome.</p>"}}]}'::jsonb, 4, 3),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'onboarding-process', 'Onboarding Process', 'Welcoming new staff', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>A strong onboarding experience sets the foundation for a great working relationship. Complete all paperwork, assign training paths, introduce the team, and check in regularly during the first few weeks. Make new staff feel welcome and supported.</p>"}}]}'::jsonb, 5, 4),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'performance-management', 'Performance Management', 'Ongoing development', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Have regular, honest conversations about performance. Recognise strengths and address areas for growth with care and specificity. Set clear expectations and follow up. Performance management is about development, not discipline.</p>"}}]}'::jsonb, 5, 5),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'staff-development', 'Staff Development', 'Growing the team', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Invest in your team. Identify potential, offer growth opportunities, and support career progression. The best teams are built by managers who genuinely want their people to succeed and grow.</p>"}}]}'::jsonb, 4, 6),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'rostering', 'Rostering', 'Building fair rosters', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Create rosters that balance business needs with staff wellbeing. Consider availability, fairness, and skill coverage. Publish rosters in advance. A well-planned roster shows respect for your team and sets service up for success.</p>"}}]}'::jsonb, 4, 7),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'labour-management', 'Labour Management', 'Managing costs wisely', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Understand labour targets and how to manage them. Balance service quality with cost efficiency. Make informed decisions about staffing levels based on bookings and forecasts. Labour management is about being smart, not cutting corners.</p>"}}]}'::jsonb, 5, 8),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'mg-venue-standards', 'Venue Standards', 'Setting and maintaining standards', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>As a manager, you define and uphold the standards of the venue. Walk the floor with attention. Address issues promptly. Lead by example. The standard you walk past is the standard you accept.</p>"}}]}'::jsonb, 4, 9),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'stock-control', 'Stock Control', 'Managing inventory', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Monitor stock levels, manage orders, and minimise waste. Conduct regular stocktakes. Build relationships with suppliers. Good stock control directly impacts the bottom line and ensures consistency for guests.</p>"}}]}'::jsonb, 4, 10),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'supplier-communication', 'Supplier Communication', 'Building partnerships', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Communicate clearly with suppliers about orders, quality expectations, and delivery schedules. Build professional relationships based on reliability and mutual respect. Good supplier partnerships support consistent quality.</p>"}}]}'::jsonb, 3, 11),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'incident-reporting', 'Incident Reporting', 'Documenting and responding', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Report all incidents promptly and thoroughly: workplace injuries, guest complaints, property damage, and safety concerns. Use the incident report template. Follow up to ensure issues are resolved and prevented.</p>"}}]}'::jsonb, 4, 12),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'cash-up-procedures', 'Cash Up Procedures', 'End of day financial', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Complete cash up procedures accurately at the end of each trading day. Count cash, reconcile with the POS, and complete the daily report. Accuracy and consistency protect the business and demonstrate professionalism.</p>"}}]}'::jsonb, 4, 13),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'financial-awareness', 'Financial Awareness', 'Understanding the numbers', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Understand the key financial metrics: revenue, labour cost, food cost, and profitability. Make decisions that consider the financial health of the business. Financial awareness at every level strengthens the organisation.</p>"}}]}'::jsonb, 5, 14),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'compliance', 'Compliance', 'Legal and regulatory', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Stay across all compliance requirements: food safety, liquor licensing, workplace health and safety, and employment law. Ensure all staff certifications are current. Compliance is not optional. It protects our team, our guests, and our business.</p>"}}]}'::jsonb, 5, 15),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'protecting-the-brand', 'Protecting The Brand', 'Brand guardianship', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>As a manager, you are a guardian of the Still and Social brand. Every decision should align with our values: presence, warmth, thoughtfulness, and care. Protect the brand in how you lead, how you serve, and how you represent us.</p>"}}]}'::jsonb, 4, 16),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'guest-experience-excellence', 'Guest Experience Excellence', 'Delivering consistently', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Drive guest experience excellence through training, standards, and personal commitment. Observe service through the eyes of the guest. Celebrate when the team delivers brilliantly. Address gaps with coaching and support.</p>"}}]}'::jsonb, 4, 17),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'leadership-standards', 'Leadership Standards', 'How we lead', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Lead with integrity, humility, and purpose. Be consistent, fair, and transparent. Admit mistakes, ask for feedback, and always strive to improve. Great leadership at Still and Social is quiet, steady, and genuine.</p>"}}]}'::jsonb, 4, 18),
('33a8ebd9-f01a-4e18-b4cf-09765ee4f1a5', 'culture-building', 'Culture Building', 'Creating the environment', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Culture is not a poster on a wall. It is the way people feel when they come to work. Build a culture of respect, support, and high standards. Celebrate wins, learn from challenges, and always put people first. The culture you build is the legacy you leave.</p>"}}]}'::jsonb, 5, 19)
ON CONFLICT (path_id, slug) DO NOTHING;
