-- Seed all training modules for Still & Social Academy
-- Path: Welcome to Still & Social
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'the-still-and-social-story', 'The Still & Social Story', 'Our story and origins', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Still and Social is a soulful world of hospitality, wellness, and ritual. Born from a belief that when we slow down, soften the noise, and return to ourselves, we feel more whole. Our Dining Sanctuary in the Dandenong Ranges is where this journey begins.</p>"}}]}'::jsonb, 3, 1),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'why-we-exist', 'Why We Exist', 'Our purpose and mission', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We exist to create spaces where people can slow down, gather with intention, and reconnect with what matters most. In a fast-paced world, we offer a sanctuary. A place to pause, to feel, and to return to yourself.</p>"}}]}'::jsonb, 3, 2),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'the-dining-sanctuary-concept', 'The Dining Sanctuary Concept', 'What makes our venue unique', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Our Dining Sanctuary is more than a restaurant. It is a retreat from the pace of the everyday, nestled in the lush green of the Dandenong Ranges. An hour from the city but a world away in feeling. Here, dining is unhurried. Seasonal menus, soulful flavours, and quiet rooms designed to slow the mind and open the senses.</p>"}}]}'::jsonb, 4, 3),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'what-makes-us-different', 'What Makes Us Different', 'Our unique approach', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We are not just a place to eat. We are a feeling. Every detail, from the tea ritual to the farewell, is designed to create a meaningful experience. We prioritise presence over pace, warmth over formality, and connection over transaction.</p>"}}]}'::jsonb, 3, 4),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'presence', 'Presence', 'Being fully here', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Being fully here, in every interaction. Not rushing to the next task, but giving each moment the attention it deserves. When we are present with our guests and each other, everything we do has more meaning.</p>"}}]}'::jsonb, 3, 5),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'warmth', 'Warmth', 'Creating welcoming spaces', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Creating an environment where everyone feels welcomed, comfortable, and at home. Warmth is not a script. It is genuine care expressed through how we greet, how we serve, and how we make people feel.</p>"}}]}'::jsonb, 3, 6),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'thoughtfulness', 'Thoughtfulness', 'Attention to detail', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Anticipating needs before they are expressed. Paying attention to the small details that elevate an experience from good to unforgettable. Thoughtfulness is the invisible thread that connects every part of our service.</p>"}}]}'::jsonb, 3, 7),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'care', 'Care', 'Pride in our work', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Taking pride in everything we do, from how we prepare a dish to how we set a table. Care means treating our workspace, our team, and our guests with respect and intention.</p>"}}]}'::jsonb, 3, 8),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'hospitality-as-care', 'Hospitality as Care', 'Our philosophy of service', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>At Still and Social, hospitality is not a transaction. It is an act of care. Every interaction is an opportunity to make someone feel seen, valued, and welcome. This is the foundation of everything we do.</p>"}}]}'::jsonb, 3, 9),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'the-feeling-we-want', 'The Feeling We Want Guests To Leave With', 'Our guest experience goal', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We want every guest to leave feeling a little more whole than when they arrived. Nourished, connected, and at peace. Not just satisfied, but genuinely moved by the experience.</p>"}}]}'::jsonb, 3, 10),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'guest-journey', 'The Still & Social Guest Journey', 'The complete guest experience', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>From the moment a guest arrives to the moment they leave, every touchpoint is intentional. The welcome, the tea ritual, the meal, the farewell. Each moment is designed to create a seamless journey of care and connection.</p>"}}]}'::jsonb, 4, 11),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'creating-meaningful-moments', 'Creating Meaningful Moments', 'The power of small gestures', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Meaningful moments are not grand gestures. They are the quiet, thoughtful details: remembering a guest name, noticing when a glass needs refilling, offering a genuine smile. These small acts create lasting impressions.</p>"}}]}'::jsonb, 3, 12),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'human-connection', 'Human Connection Through Hospitality', 'Connecting genuinely', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>At its core, hospitality is about human connection. It is about making people feel that they matter. Every interaction is an opportunity to connect genuinely, warmly, and with presence.</p>"}}]}'::jsonb, 3, 13),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'communication-standards', 'Communication Standards', 'How we communicate', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clear, respectful, and timely communication is essential. We speak directly, listen actively, and always assume good intent. On the floor, we communicate calmly and efficiently. Behind the scenes, we are honest and supportive.</p>"}}]}'::jsonb, 3, 14),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'respect-and-professionalism', 'Respect and Professionalism', 'Our professional standards', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We treat every team member with dignity and respect, regardless of role or experience. We are punctual, prepared, and professional. We support each other and hold ourselves to a high standard.</p>"}}]}'::jsonb, 3, 15),
('c6bbf010-551d-4653-a725-928d5e98f5a9', 'team-expectations', 'Team Expectations', 'What we expect from each other', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We show up on time, in full uniform, ready to work. We communicate openly. We support each other during service. We take pride in our venue and our work. We are always learning and growing.</p>"}}]}'::jsonb, 3, 16)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Path: FOH Sequence of Service
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-1-welcome', 'Step 1: Welcome', 'Greeting and first impressions', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Greeting guests with genuine warmth. Making eye contact, smiling naturally, and confirming their booking. First impressions set the tone for the entire experience. Escort guests to their table with care and attention.</p>"}}]}'::jsonb, 4, 1),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-2-tea-ritual', 'Step 2: Tea Ritual', 'The signature tea offering', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>We offer every guest a complimentary tea as they settle in. This is not just a drink. It is a ritual. Present it with intention, explain the offering, and allow the moment to create calm. The tea ritual sets the pace for the entire dining experience.</p>"}}]}'::jsonb, 4, 2),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-3-water-ritual', 'Step 3: Water Ritual', 'Water service standards', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Offer still or sparkling water. Pour attentively. Refill without being asked. Water service is a constant touchpoint. Use it to maintain connection and show attention to detail throughout the meal.</p>"}}]}'::jsonb, 3, 3),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-4-menu-introduction', 'Step 4: Menu Introduction', 'Presenting the dining concept', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Explain our dining concept clearly and warmly. Walk guests through the menu structure, highlight seasonal specials, and ask about dietary requirements. Knowledge and confidence are key. Make guests feel guided, not overwhelmed.</p>"}}]}'::jsonb, 4, 4),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-5-drinks-service', 'Step 5: Drinks Service', 'Taking and serving drinks', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Take drink orders with attentiveness. Make genuine recommendations based on guest preferences. Engage naturally. This is a moment of connection, not just an order. Serve drinks with care and precision.</p>"}}]}'::jsonb, 4, 5),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-6-food-ordering', 'Step 6: Food Ordering', 'Taking food orders', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Take food orders accurately and confidently. Upsell naturally by sharing your genuine favourites. Be thorough with allergy awareness. Repeat orders back to confirm. Accuracy and warmth go hand in hand.</p>"}}]}'::jsonb, 4, 6),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-7-during-service', 'Step 7: During Service', 'Maintaining the experience', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Maintain tables with quiet efficiency. Read the table. Are guests deep in conversation or ready for the next course? Anticipate needs before they arise. Clear plates, refresh drinks, adjust settings. Be present without being intrusive.</p>"}}]}'::jsonb, 4, 7),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-8-guest-check-in', 'Step 8: Guest Check-In', 'Checking on the experience', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Time your check-in thoughtfully. Ask genuinely about their experience. Listen to feedback with openness. A well-timed check-in shows care without interrupting the flow of the meal.</p>"}}]}'::jsonb, 3, 8),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-9-hot-towel-ritual', 'Step 9: Hot Towel Ritual', 'The signature finishing touch', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Present hot towels with care at the end of the meal. This is a signature Still and Social touch. The timing and presentation should feel considered and premium. It is a small gesture that leaves a lasting impression.</p>"}}]}'::jsonb, 3, 9),
('407fbb58-d38c-4f2d-9a33-395b388778f3', 'step-10-farewell', 'Step 10: Farewell', 'Creating lasting impressions', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Thank guests sincerely. Invite them to return. Walk them toward the door when possible. The farewell is the last impression. Make it warm, personal, and memorable. Leave them feeling valued.</p>"}}]}'::jsonb, 3, 10)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Path: Waiter Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('df650b24-3e74-4148-b2ac-874299a621b9', 'table-service-standards', 'Table Service Standards', 'Excellence at the table', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Table service at Still and Social is defined by attentiveness, warmth, and precision. Approach each table with presence. Serve from the correct side, clear efficiently, and maintain a clean, welcoming table throughout the meal.</p>"}}]}'::jsonb, 4, 1),
('df650b24-3e74-4148-b2ac-874299a621b9', 'taking-orders', 'Taking Orders', 'Accurate and confident ordering', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Take orders with clarity and confidence. Listen carefully, write clearly, and repeat back to confirm. Pay attention to dietary requirements, allergies, and preferences. Accuracy is essential. Every order is a promise to the guest.</p>"}}]}'::jsonb, 4, 2),
('df650b24-3e74-4148-b2ac-874299a621b9', 'menu-recommendations', 'Menu Recommendations', 'Sharing knowledge naturally', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Know the menu deeply. Share recommendations from genuine experience. When a guest asks what you suggest, answer with honesty and warmth. Highlight seasonal specials, chef favourites, and dishes you personally enjoy. Authenticity builds trust.</p>"}}]}'::jsonb, 4, 3),
('df650b24-3e74-4148-b2ac-874299a621b9', 'dietary-questions', 'Dietary Questions', 'Handling dietary needs with care', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Always ask about dietary requirements early in the ordering process. Listen without judgement. Know which dishes can be modified and which cannot. When unsure, check with the kitchen. Never guess. Dietary awareness is a matter of guest safety and trust.</p>"}}]}'::jsonb, 4, 4),
('df650b24-3e74-4148-b2ac-874299a621b9', 'guest-check-ins', 'Guest Check-Ins', 'Timing and approach', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Check in after the first few bites of the main course. Read the table before approaching. Keep it brief and genuine. A simple question shows you care. If feedback is given, listen fully and act on it.</p>"}}]}'::jsonb, 3, 5),
('df650b24-3e74-4148-b2ac-874299a621b9', 'clearing-tables', 'Clearing Tables', 'Clean and efficient clearing', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clear plates only when all guests at the table have finished. Approach quietly and efficiently. Stack plates carefully, never scrape food in front of guests. Clearing should feel seamless, not disruptive.</p>"}}]}'::jsonb, 3, 6),
('df650b24-3e74-4148-b2ac-874299a621b9', 'resetting-tables', 'Resetting Tables', 'Preparing for the next guest', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Reset tables promptly and with care. Every setting should be aligned, every glass polished, every surface clean. A well-set table communicates that we are ready and that we care about the details. Reset as if every table is the first of the evening.</p>"}}]}'::jsonb, 3, 7),
('df650b24-3e74-4148-b2ac-874299a621b9', 'upselling-naturally', 'Upselling Naturally', 'Enhancing the experience', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Upselling at Still and Social is not about pushing products. It is about enhancing the guest experience. Suggest a wine pairing that complements their meal. Mention a dessert that pairs beautifully with their tea. When upselling feels natural, it adds value.</p>"}}]}'::jsonb, 3, 8),
('df650b24-3e74-4148-b2ac-874299a621b9', 'guest-experience-standards', 'Guest Experience Standards', 'The full picture', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Every interaction shapes the guest experience. From the warmth of your greeting to the sincerity of your farewell, every moment matters. Hold yourself to the highest standard. Be present, be genuine, and always aim to leave guests feeling more whole than when they arrived.</p>"}}]}'::jsonb, 4, 9)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Path: All-Rounder Training
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'hosting-and-greeting', 'Hosting and Greeting', 'First point of contact', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>As an all-rounder, you may be the first person a guest meets. Greet every guest with a warm smile and genuine welcome. Confirm their booking calmly. Make them feel expected and valued from the very first moment.</p>"}}]}'::jsonb, 3, 1),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'seating-guests', 'Seating Guests', 'Guiding with care', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Walk guests to their table at a comfortable pace. Pull out chairs when appropriate. Offer a brief orientation of the space. Ensure the table is set and ready before seating. First impressions begin with how we guide.</p>"}}]}'::jsonb, 3, 2),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'running-food', 'Running Food', 'Delivering with precision', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Run food promptly and to the correct table. Confirm dishes with the guest before placing. Handle plates with care and present them thoughtfully. Running food is not just delivery. It is part of the experience.</p>"}}]}'::jsonb, 3, 3),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'clearing-tables-ar', 'Clearing Tables', 'Efficient and respectful', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Clear tables efficiently without disrupting conversation. Wait until all guests have finished before clearing. Stack carefully and quietly. A clean table shows attentiveness and care.</p>"}}]}'::jsonb, 3, 4),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'supporting-waiters', 'Supporting Waiters', 'Teamwork on the floor', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Anticipate what waiters need before they ask. Refill water, clear plates, reset tables. Be aware of the flow of service. Supporting waiters means the guest experience stays seamless, even during busy periods.</p>"}}]}'::jsonb, 3, 5),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'supporting-bar', 'Supporting Bar', 'Helping behind the bar', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Support the bar team by restocking glassware, clearing used glasses, and keeping the bar area tidy. Learn basic drink running so you can deliver drinks to tables when needed. Communication with the bartender is key.</p>"}}]}'::jsonb, 3, 6),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'basic-drinks-running', 'Basic Drinks Running', 'Getting drinks to tables', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Carry drinks safely using a tray when possible. Confirm the table number before delivering. Place drinks carefully, from the right side when practical. Ensure the correct drink reaches the correct guest.</p>"}}]}'::jsonb, 3, 7),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'takeaway-procedures', 'Takeaway Procedures', 'Handling takeaway orders', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Process takeaway orders accurately. Package food with care and presentation in mind. Include all necessary items: cutlery, napkins, sauces. Even takeaway guests deserve the Still and Social experience.</p>"}}]}'::jsonb, 3, 8),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'venue-presentation', 'Venue Presentation', 'Maintaining the space', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>The venue should always look its best. Straighten chairs, wipe surfaces, check bathrooms regularly. Presentation is constant. A well-maintained venue tells guests that we care about every detail of their experience.</p>"}}]}'::jsonb, 3, 9),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'opening-duties', 'Opening Duties', 'Setting up for service', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Arrive on time and ready to work. Follow the opening checklist: set tables, check bathrooms, prepare the floor. Ensure everything is in place before the first guest arrives. A calm opening leads to a smooth service.</p>"}}]}'::jsonb, 4, 10),
('5aed9b32-4e84-4ba6-a2af-574972f7c730', 'closing-duties', 'Closing Duties', 'End of night procedures', 'text', '{"blocks":[{"type":"text","data":{"html":"<p>Follow the closing checklist carefully. Reset all tables for the next service. Clean and restock stations. Check that all areas are tidy and secure. Closing well means opening well tomorrow.</p>"}}]}'::jsonb, 4, 11)
ON CONFLICT (path_id, slug) DO NOTHING;
