-- The Still & Social Way modules
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'our-story', 'Our Story', 'Where it all began', 'text', '{"blocks":[{"type":"heading","data":{"text":"Our Story","level":2}},{"type":"text","data":{"html":"<p>Still and Social was born from a simple belief. That when we slow down, soften the noise, and return to ourselves, we feel more whole. Our Dining Sanctuary in the Dandenong Ranges is where this journey begins. An hour from the city, a world away in feeling.</p>"}},{"type":"quote","data":{"text":"A soulful sanctuary in a fast-paced world.","attribution":"Still and Social"}}]}'::jsonb, 5, 1),
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'why-we-exist-way', 'Why We Exist', 'Our purpose', 'text', '{"blocks":[{"type":"heading","data":{"text":"Why We Exist","level":2}},{"type":"text","data":{"html":"<p>We exist to create spaces where people can slow down, gather with intention, and reconnect with what matters most. Every dish we serve, every interaction we have, every moment we create is guided by this purpose.</p>"}}]}'::jsonb, 4, 2),
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'ritual-of-good-living', 'Ritual of Good Living', 'Our philosophy', 'text', '{"blocks":[{"type":"heading","data":{"text":"The Ritual of Good Living","level":2}},{"type":"text","data":{"html":"<p>The Ritual of Good Living is not a destination to reach. It is a way of being. A reminder to slow down when we can. To appreciate what is already here. To find beauty in the ordinary. And to create space for the things that matter most.</p>"}},{"type":"tip","data":{"title":"What this means for you","text":"Every shift is an opportunity to embody this philosophy. In how you greet, how you serve, and how you connect with the people around you."}}]}'::jsonb, 5, 3),
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'how-we-care-for-guests', 'How We Care For Guests', 'Our guest philosophy', 'text', '{"blocks":[{"type":"heading","data":{"text":"How We Care For Guests","level":2}},{"type":"text","data":{"html":"<p>Caring for guests at Still and Social goes beyond good service. It means being genuinely interested in their experience. It means anticipating their needs. It means making them feel that they matter, not as customers, but as people.</p>"}},{"type":"steps","data":{"items":[{"title":"See them","description":"Notice every guest. Acknowledge their presence immediately."},{"title":"Welcome them","description":"Make them feel expected and valued from the first moment."},{"title":"Care for them","description":"Attend to their needs with genuine warmth throughout."},{"title":"Thank them","description":"End their experience with sincerity and an invitation to return."}]}}]}'::jsonb, 5, 4),
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'how-we-care-for-each-other', 'How We Care For Each Other', 'Our team culture', 'text', '{"blocks":[{"type":"heading","data":{"text":"How We Care For Each Other","level":2}},{"type":"text","data":{"html":"<p>The way we treat each other behind the scenes shapes the experience we create for guests. A team that supports each other, communicates openly, and lifts each other up creates an environment where great hospitality happens naturally.</p>"}},{"type":"comparison","data":{"before":{"label":"Instead of this","text":"Working in silence, ignoring when a teammate is struggling, focusing only on your own section."},"after":{"label":"Try this","text":"Checking in with each other, offering help before being asked, celebrating wins together."}}}]}'::jsonb, 5, 5),
('82b6dc29-8296-44eb-b626-53fd0b1ea466', 'what-great-hospitality-looks-like', 'What Great Hospitality Looks Like', 'Our standard', 'text', '{"blocks":[{"type":"heading","data":{"text":"What Great Hospitality Looks Like","level":2}},{"type":"text","data":{"html":"<p>Great hospitality is not about perfection. It is about presence. It is about making someone feel genuinely cared for. It is the difference between a meal and an experience. Between a visit and a memory.</p>"}},{"type":"scenario","data":{"situation":"A guest looks uncertain as they enter the restaurant. They seem to be searching for someone or unsure where to go.","options":[{"text":"Wait for them to approach the host stand","correct":false,"feedback":"Waiting puts the burden on the guest. We should always approach first."},{"text":"Walk over, make eye contact, and warmly welcome them","correct":true,"feedback":"This is exactly right. Taking the initiative shows care and makes them feel expected."},{"text":"Point them to the host stand from across the room","correct":false,"feedback":"Pointing feels impersonal. A warm approach creates connection."}]}}]}'::jsonb, 6, 6)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Rituals of Hospitality modules
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('106572a0-c16c-4b81-8641-98e0e2ede6f2', 'ritual-1-the-welcome', 'Ritual 1: The Welcome', 'How guests feel in the first 30 seconds', 'text', '{"blocks":[{"type":"heading","data":{"text":"The Welcome","level":2}},{"type":"text","data":{"html":"<p>The first 30 seconds of a guest experience shape everything that follows. A genuine welcome tells the guest: you are expected, you are valued, you belong here. This is not about scripts. It is about presence.</p>"}},{"type":"timeline","data":{"items":[{"time":"0 sec","title":"Eye Contact","description":"Notice the guest immediately. Smile naturally."},{"time":"5 sec","title":"Approach","description":"Walk toward them with warmth. Do not wait for them to come to you."},{"time":"10 sec","title":"Greet","description":"Welcome them warmly. Use their name if you know their booking."},{"time":"20 sec","title":"Guide","description":"Walk them to their table at a comfortable pace."},{"time":"30 sec","title":"Settle","description":"Help them settle in. Offer the tea ritual."}]}},{"type":"callout","data":{"text":"The welcome is not a task to complete. It is a feeling to create. Every guest should feel that their arrival was the best part of your day.","type":"info"}}]}'::jsonb, 6, 1),
('106572a0-c16c-4b81-8641-98e0e2ede6f2', 'ritual-2-presence', 'Ritual 2: Presence', 'Being fully present with guests', 'text', '{"blocks":[{"type":"heading","data":{"text":"Presence","level":2}},{"type":"text","data":{"html":"<p>Presence is the art of being fully here. Not thinking about the next table. Not checking the time. Not going through the motions. When you are truly present with a guest, they feel it. And it changes everything.</p>"}},{"type":"flipcards","data":{"items":[{"front":"What presence looks like","back":"Making eye contact. Listening fully. Responding to what is said, not what you expect to hear. Being unhurried even when busy."},{"front":"What absence looks like","back":"Scanning the room while talking. Rushing through explanations. Forgetting details. Making guests repeat themselves."},{"front":"How to practice","back":"Before approaching a table, take one breath. Remind yourself: this table is the only one that matters right now."}]}}]}'::jsonb, 6, 2),
('106572a0-c16c-4b81-8641-98e0e2ede6f2', 'ritual-3-anticipation', 'Ritual 3: Anticipation', 'Recognising needs before guests ask', 'text', '{"blocks":[{"type":"heading","data":{"text":"Anticipation","level":2}},{"type":"text","data":{"html":"<p>The highest level of hospitality is anticipating what a guest needs before they know they need it. A water refill before the glass is empty. A menu suggestion before they feel lost. A check-in at exactly the right moment.</p>"}},{"type":"scenario","data":{"situation":"You notice a guest has been looking at the menu for several minutes, occasionally glancing around the room.","options":[{"text":"Give them more time, they will ask when ready","correct":false,"feedback":"While patience is good, prolonged indecision often means they need guidance."},{"text":"Approach and ask if they have any questions about the menu","correct":true,"feedback":"A gentle offer of help shows you are paying attention without being pushy."},{"text":"Send another staff member to check on them","correct":false,"feedback":"Personal continuity matters. If you noticed, you should be the one to help."}]}}]}'::jsonb, 6, 3),
('106572a0-c16c-4b81-8641-98e0e2ede6f2', 'ritual-4-care', 'Ritual 4: Care', 'Making guests feel genuinely looked after', 'text', '{"blocks":[{"type":"heading","data":{"text":"Care","level":2}},{"type":"text","data":{"html":"<p>Care is what separates good service from great hospitality. It is the difference between doing your job and genuinely looking after someone. Care is not performative. It comes from a real desire to make someone else experience better.</p>"}},{"type":"steps","data":{"items":[{"title":"Remember details","description":"A regular guest preference. A birthday. An allergy from last visit. These details show you care."},{"title":"Go beyond the expected","description":"A warm towel on a cold night. A recommendation that perfectly matches their mood. These extras create memories."},{"title":"Handle problems with grace","description":"When something goes wrong, care means owning it fully, resolving it genuinely, and following up sincerely."}]}}]}'::jsonb, 6, 4),
('106572a0-c16c-4b81-8641-98e0e2ede6f2', 'ritual-5-the-farewell', 'Ritual 5: The Farewell', 'Creating memorable final impressions', 'text', '{"blocks":[{"type":"heading","data":{"text":"The Farewell","level":2}},{"type":"text","data":{"html":"<p>The farewell is the last moment a guest carries with them. It is what they remember on the drive home. It is what they tell their friends about. A great farewell transforms a good meal into a lasting memory.</p>"}},{"type":"comparison","data":{"before":{"label":"A forgettable farewell","text":"Dropping the bill, processing payment, saying thanks without eye contact, turning to the next task."},"after":{"label":"A memorable farewell","text":"Thanking them sincerely by name. Walking them toward the door. Telling them it was a genuine pleasure. Inviting them to return. Making them feel that their visit mattered."}}},{"type":"quote","data":{"text":"Come as you are. Leave a little more whole.","attribution":"Still and Social"}}]}'::jsonb, 6, 5)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Event Training modules
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('465f1bd4-3c02-4656-a7bb-c4e7a572671f', 'wine-and-soul', 'Wine & Soul', 'Our signature tasting events', 'text', '{"blocks":[{"type":"heading","data":{"text":"Wine and Soul Evenings","level":2}},{"type":"text","data":{"html":"<p>Wine and Soul is our signature event series. An evening of curated wines, paired with thoughtful dishes, in an intimate setting. The atmosphere is relaxed, the conversation flows, and the experience feels personal.</p>"}}]}'::jsonb, 5, 1),
('465f1bd4-3c02-4656-a7bb-c4e7a572671f', 'private-functions', 'Private Functions', 'Hosting private events', 'text', '{"blocks":[{"type":"heading","data":{"text":"Private Functions","level":2}},{"type":"text","data":{"html":"<p>Private functions require elevated attention to detail. From the initial enquiry to the event itself, every touchpoint should feel considered and personal. The host should feel that their event is the most important thing happening.</p>"}}]}'::jsonb, 5, 2),
('465f1bd4-3c02-4656-a7bb-c4e7a572671f', 'workshops', 'Workshops', 'Interactive learning experiences', 'text', '{"blocks":[{"type":"heading","data":{"text":"Workshops","level":2}},{"type":"text","data":{"html":"<p>Workshops at Still and Social are immersive experiences. Whether it is a cooking class, a cocktail masterclass, or a wellness session, the goal is always the same: to create a meaningful, hands-on experience that guests carry with them.</p>"}}]}'::jsonb, 4, 3),
('465f1bd4-3c02-4656-a7bb-c4e7a572671f', 'community-events', 'Community Events', 'Connecting with our community', 'text', '{"blocks":[{"type":"heading","data":{"text":"Community Events","level":2}},{"type":"text","data":{"html":"<p>Community events connect Still and Social with the people and places around us. These events are about giving back, building relationships, and strengthening our place in the local community.</p>"}}]}'::jsonb, 4, 4),
('465f1bd4-3c02-4656-a7bb-c4e7a572671f', 'event-setup-packdown', 'Event Setup & Pack Down', 'Before and after', 'text', '{"blocks":[{"type":"heading","data":{"text":"Event Setup and Pack Down","level":2}},{"type":"text","data":{"html":"<p>A well-executed event starts with thorough setup and ends with careful pack down. Follow the event checklist for each type of event. Arrive early, prepare with care, and leave the venue in perfect condition.</p>"}},{"type":"checklist","data":{"items":["Venue layout confirmed and set","Audio and visual equipment tested","Table settings complete","Welcome area prepared","Signage in place","Staff briefed on running order","Pack down checklist ready"]}}]}'::jsonb, 5, 5)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Leadership Academy modules
INSERT INTO academy_training_modules (path_id, slug, title, description, content_type, content, estimated_minutes, sort_order) VALUES
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'leadership-foundations', 'Leadership Foundations', 'What it means to lead at Still and Social', 'text', '{"blocks":[{"type":"heading","data":{"text":"Leadership Foundations","level":2}},{"type":"text","data":{"html":"<p>Leadership at Still and Social is not about authority. It is about influence, care, and accountability. The best leaders create environments where people want to do their best work. They lead by example, communicate with clarity, and always put people first.</p>"}}]}'::jsonb, 5, 1),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'coaching-and-feedback', 'Coaching & Feedback', 'Developing your team', 'text', '{"blocks":[{"type":"heading","data":{"text":"Coaching and Feedback","level":2}},{"type":"text","data":{"html":"<p>Great leaders are great coaches. Coaching is not about telling people what to do. It is about asking the right questions, listening deeply, and helping people find their own answers. Feedback should be specific, timely, and always delivered with care.</p>"}}]}'::jsonb, 5, 2),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'difficult-conversations', 'Difficult Conversations', 'Handling tough moments', 'text', '{"blocks":[{"type":"heading","data":{"text":"Difficult Conversations","level":2}},{"type":"text","data":{"html":"<p>Difficult conversations are part of leadership. Whether it is addressing performance, managing conflict, or delivering tough news, the key is to approach with empathy, clarity, and respect. Avoid them and small issues become big ones.</p>"}}]}'::jsonb, 5, 3),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'hiring-and-interviews', 'Hiring & Interviews', 'Finding the right people', 'text', '{"blocks":[{"type":"heading","data":{"text":"Hiring and Interviews","level":2}},{"type":"text","data":{"html":"<p>Hiring is one of the most important things a leader does. The people you bring in shape the culture. Recruit for values first, skills second. Look for warmth, reliability, and a genuine desire to care for others.</p>"}}]}'::jsonb, 5, 4),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'la-rostering', 'Rostering', 'Building fair and effective rosters', 'text', '{"blocks":[{"type":"heading","data":{"text":"Rostering","level":2}},{"type":"text","data":{"html":"<p>A good roster balances business needs with team wellbeing. Consider availability, fairness, skill coverage, and fatigue management. Publish rosters in advance. A well-planned roster shows respect for your team.</p>"}}]}'::jsonb, 4, 5),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'team-development', 'Team Development', 'Growing your people', 'text', '{"blocks":[{"type":"heading","data":{"text":"Team Development","level":2}},{"type":"text","data":{"html":"<p>The best teams are built by leaders who genuinely want their people to succeed. Identify potential, offer growth opportunities, and support career progression. Invest in your team and they will invest in the business.</p>"}}]}'::jsonb, 5, 6),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'conflict-resolution', 'Conflict Resolution', 'Managing disagreements', 'text', '{"blocks":[{"type":"heading","data":{"text":"Conflict Resolution","level":2}},{"type":"text","data":{"html":"<p>Conflict is natural in any team. How you handle it defines your leadership. Listen to all sides. Stay neutral. Focus on resolution, not blame. Address issues early before they escalate. Create an environment where people feel safe to raise concerns.</p>"}}]}'::jsonb, 5, 7),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'financial-awareness-la', 'Financial Awareness', 'Understanding the numbers', 'text', '{"blocks":[{"type":"heading","data":{"text":"Financial Awareness","level":2}},{"type":"text","data":{"html":"<p>Understanding the financial health of the business helps you make better decisions. Know the key metrics: revenue, labour cost, food cost, and profitability. Financial awareness at every level strengthens the organisation.</p>"}}]}'::jsonb, 5, 8),
('730bf732-60fe-4209-ad63-af6e1026dc6a', 'business-operations', 'Business Operations', 'Running the venue', 'text', '{"blocks":[{"type":"heading","data":{"text":"Business Operations","level":2}},{"type":"text","data":{"html":"<p>Operational excellence is the foundation of a great venue. From stock management to supplier relationships, from compliance to daily reporting, every operational detail contributes to the guest experience and the health of the business.</p>"}}]}'::jsonb, 5, 9)
ON CONFLICT (path_id, slug) DO NOTHING;

-- Assign new pathways to roles
INSERT INTO academy_role_training_paths (role, path_id, is_required, sort_order) VALUES
-- The Still & Social Way - mandatory for everyone (sort 0 = first)
('waiter', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('restaurant_all_rounder', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('bartender', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('kitchen_hand', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('entree_chef', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('wok_chef', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('curries_chef', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('expo_chef', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('supervisor', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
('manager', '82b6dc29-8296-44eb-b626-53fd0b1ea466', true, 0),
-- Rituals of Hospitality - FOH + Leadership
('waiter', '106572a0-c16c-4b81-8641-98e0e2ede6f2', true, 4),
('restaurant_all_rounder', '106572a0-c16c-4b81-8641-98e0e2ede6f2', true, 4),
('bartender', '106572a0-c16c-4b81-8641-98e0e2ede6f2', true, 4),
('supervisor', '106572a0-c16c-4b81-8641-98e0e2ede6f2', true, 4),
('manager', '106572a0-c16c-4b81-8641-98e0e2ede6f2', true, 4),
-- Event Training - FOH + Leadership
('waiter', '465f1bd4-3c02-4656-a7bb-c4e7a572671f', false, 5),
('restaurant_all_rounder', '465f1bd4-3c02-4656-a7bb-c4e7a572671f', false, 5),
('bartender', '465f1bd4-3c02-4656-a7bb-c4e7a572671f', false, 5),
('supervisor', '465f1bd4-3c02-4656-a7bb-c4e7a572671f', false, 5),
('manager', '465f1bd4-3c02-4656-a7bb-c4e7a572671f', false, 5),
-- Leadership Academy - supervisors + managers
('supervisor', '730bf732-60fe-4209-ad63-af6e1026dc6a', true, 5),
('manager', '730bf732-60fe-4209-ad63-af6e1026dc6a', true, 4)
ON CONFLICT (role, path_id) DO NOTHING;
